API cleanup regarding `Get()` returning interfaces
synadia-io/jwt-auth-builder.go pull request #37
Opened 2024-02-28 15:56 UTC by aricart

[CHANGE] auth.Operators().Get(name) now returns (Operator,bool) - this bypasses annoying go returning non-nil when interface.

2024-02-29 13:03 UTC, aricart commented
@ripienaar this is a PITA change for you, but I think it is the right thing to do by the API - anywhere we return an interface from a Get/GetByName and the likes, a boolean argument will tell you if the get succeeded. Otherwise checks with nil require reflection, I think this is friendlier API. Some Gets remain as they return concrete types, for those the nil checks are safe in user code.

2024-03-06 19:19 UTC, aricart commented
@ripienaar changed so that the bool arguments become error if it is not found. Also added API for knowing if a signing key is present and whether it is scoped.

2024-03-08 12:24 UTC, ripienaar requested changes
small consistency notes

2024-03-08 13:35 UTC, aricart commented on account_signingkeys.go
> +func (as *accountSigningKeys) Contains(sk string) (bool, bool) {
one is has the signing key, the other that signing key is scoped.

2024-03-08 14:40 UTC, ripienaar commented on service_imports.go
> +func (s *serviceImports) Get(subject string) (ServiceImport, bool) {
Still got this one and similar one below @aricart

2024-03-08 14:41 UTC, aricart commented on service_imports.go
> +func (s *serviceImports) GetByName(name string) (ServiceImport, bool) {
oops

2024-03-08 14:54 UTC, ripienaar approved these changes
LGTM

2024-03-08 17:07 UTC, merged